### ISSUE TITLE
Rodčenko_2022 by totem

### ISSUE THREAD

**Issue by TOTEM4R7** [teia-community/teia-blog#39]
**Fundraising NFT for Ukraine on TEIA:**

**Description:**

**[URL](https://teia.art/objkt/701825):**

**To help our community partecipate in fundraising for Ukraine people**

***Include an image to be displayed with the link***![Rodčenko_2022](https://user-images.githubusercontent.com/102109620/159376941-556e513c-f6c5-40ff-8dd6-bc0a1e32ed13.jpg)

**Comment by kylegrover** [comment]
It will get messy fast to host NFTs in the links list, but I think @merchantcoppola has an idea for where this should go

**Comment by kylegrover** [comment]
closing for now but we can still discuss it here and reopen if that makes sense
