### ISSUE TITLE
Add Mastodon link to link page

### ISSUE THREAD

**Issue by merchantcoppola** [teia-community/teia-blog#68]
**Title: Teias Mastodon Server**

**Description: Mastodon instance run for and by the community. Open to everyone, NFT art posts encouraged! Mastodon is an open-sourced, decentralized social media software.**

**URL: https://mastodon.teia.art/**

**Why should this link be added?**

***Include an image to be displayed with the link: https://commons.wikimedia.org/wiki/File:Mastodon_Logotype_(Simple).svg***

**Comment by kylegrover** [comment]
[7f57d0e](https://github.com/teia-community/teia-blog/commit/7f57d0e0806fea455f87e5e78352bd565d8a16e5)
